       
name: deploy tinvol.github.io website
on:
  push:
    branches: [ supremeMeme2 ]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository-name: tinvol/tinvol.github.io
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
